production:
  adapter: postgresql
  database: lportal
  username: lportal_user
  password: lportal
  host: 127.0.0.1
  timeout: 5000

test:
  adapter: postgresql
  database: lportal_test
  username: rails_tester
  password: rails
  host: 127.0.0.1
  timeout: 5000

